FROM jwilder/dockerize
RUN apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip && \
    rm -r /root/.cache
ADD requirements.txt /usr/src/app/requirements.txt
ADD ./test_celery/ /usr/src/app/test_celery
WORKDIR /usr/src/app/
RUN pip3 install -r requirements.txt
ENV C_FORCE_ROOT 1
ENTRYPOINT dockerize -wait tcp://rabbit:5672 python3.6 -m test_celery.run_tasks
