version: '3.4'
services:
    rabbit:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
        ports:
            - "5673:5673"

    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        links:
            - rabbit
        depends_on:
            - rabbit
        environment:
            - C_FORCE_ROOT=1

    producer:
        build:
            context: .
            dockerfile: Dockerfile.producer
        depends_on:
            - rabbit
            - worker

    database:
        image: mongo:latest
        ports:
            - "27018:27018"
