version: '2'
services:
    rabbit:
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
        ports:
            - "5673:5672"

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - rabbit
        depends_on:
            - rabbit
        environment:
            - C_FORCE_ROOT=1

    database:
        image: mongo:latest
        ports:
            - "27018:27017"
