version: '2'
services:
    rabbit:
        hostname: localhost
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
        ports:
            - "5673:5672"

    worker:
        hostname: localhost
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        links:
            - rabbit
        depends_on:
            - rabbit

    database:
        hostname: mongo
        image: mongo:latest
        ports:
            - "27018:27017"
